version: "3.0"
services:
  healthcheck:
    image: ghcr.io/matus-barta/healthcheck:latest
    container_name: healthcheck
    environment:
      - PORT=8082            # listening port
      - HOST="localhost"     # listening IP address
      - ROOT_RES="true"      # https://<domain>/
      - ENDPOINT_RES="false" # https://<domain>/healthcheck
      - JSON_RES="true"      # response in JSON
    ports:
      - 8082:8082
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true